language: c
sudo: false

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.9.1
    - CRYSTAL_VERSION=0.10.2
    - CRYSTAL_VERSION=0.11.1
    - CRYSTAL_VERSION=0.12.0
    - CRYSTAL_VERSION=0.13.0
    - CRYSTAL_VERSION=0.14.2
    - CRYSTAL_VERSION=0.15.0

install:
  - curl -L https://raw.github.com/pine613/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version

before_script:
  - make install

script:
  - make test
